# Generated by Django 4.0.6 on 2022-07-12 22:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: ###-###-####', regex='^\\d{3}-\\d{3}-\\d{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterapp.shelter')),
            ],
        ),
    ]
